README.md, package.json, pages/CharityPortalCheckBalancePage.js, pages/CheckoutRegistrationPage.js, pages/CheckoutSuccessPage.js, pages/CheckoutWebhookPage.js, pages/DonatePage.js, steps/donation.js, support/action.js, support/check.js, support/checkout/webhook.js, support/constants.js, support/util.js, wdio.BASE.conf.js, yarn.lock
* use `@wdio/sync` to avoid explicit `await` / `async` in most cases, and make failure of async calls fail tests
* simplify + remove fixed waits where enabled by this change
* bring back + fix/update thanks/receipt amount check
* replace T&Cs checkbox label workaround
* reduce maximum wait to 20 seconds
* remove unused fns & todos
=> REG-4 - fix and simplify tests

pages/CharityPortalLoginPage.js, pages/CheckoutRegistrationPage.js
- Update title and page heading check
- Update charity portal login page placeholder selector to username after OPS-390
=> Update title and page heading check

pages/DonateStartPage.js, steps/donation.js
Also update the selectors used to check for and interact with this and make it more resilient
=> REG-9 - update where we check for no funds modal

.circleci/config.yml, docker-compose.yml
See https://stackoverflow.com/a/67383621/2803757
=> REG-18 - pin CircleCI base Node image to v14

.circleci/config.yml, README.md, package.json, pages/ChampionPortalAllocateFunds.js, pages/CharityPortalCheckBalancePage.js, pages/CharityPortalLoginPage.js, pages/DonateStartPage.js, pages/DonateSuccessPage.js, pages/PledgeFormPage.js, steps/champion.js, steps/donation.js, steps/hooks.js, steps/pledge.js, support/action.js, support/check.js, support/mailtrap.js, support/util.js, wdio.BASE.conf.ts, wdio.testingbot-all.conf.js, wdio.testingbot-chrome.conf.js, wdio.testingbot-edge.conf.js, yarn.lock
And upgrade stuff:
* Webdriver.io libraries to v7
* CI Node runner to v18
=> REG-22 – migrate to async

features/donation-as-new-donor-then-register.feature
Tests were failing because I had forgotten to tell the test to wait before checking the email.
=> REG-26 Added 'When I wait a few seconds for email processing' and tweaked test name

.eslintrc.yaml, pages/ChampionPortalAllocateFunds.js, pages/CharityPortalCheckBalancePage.js, pages/CharityPortalLoginPage.js, pages/DonateStartPage.js, pages/DonateSuccessPage.js, pages/PledgeFormPage.js
See https://github.com/thebiggive/regression-tests/pull/82#pullrequestreview-1223062188
=> Remove require js-doc rule from linter

package-lock.json, package.json, pages/DonateStartPage.js, yarn.lock
We now throw error if Axe detects any accessibility violation on the form submission page except the three that we know are there currently: 'landmark-unique', 'page-has-heading-one', 'region', plus an issue about contrast within the twitter share link.
=> REG-23: Throw error when Accessibility check fails

pages/DonateSuccessPage.js
0123456789 is no longer allowed as a password, since HiBP identifies it as having been part of a password data breach
=> ID-36: Use random 20 character password in regression tests

features/donation-as-new-donor-restart-donation.feature, features/donation-as-new-donor-then-register.feature, features/donation-with-credits.feature, features/donation-with-saved-info.feature, features/submit-pledge.feature, pages/DonateSuccessPage.js, steps/donation.js, support/mailtrap.js
…xing one at a time
This involves some changes to the tests that mean they might not be quite as good as they were before they started failing, but at the moment everything is failing so we effectively have no tests. Something is better than nothing.
Merging this doesn't mean the ticket can be considered done.
=> REG-33: Get regression tests passing again

steps/donation.js
This should start passing once https://github.com/thebiggive/donate-frontend/pull/1019 is deployed to staging env
=> REG-33: Stop forcing browser refresh on thanks page

features/donation-as-new-donor-restart-donation.feature
Reverts thebiggive/regression-tests#116
This test should start passing again thanks to https://github.com/thebiggive/donate-frontend/pull/1286 being merged.
=> Revert "Skip test for feature known to be broken - see ticket DON-883"

features/donation-as-new-donor-restart-donation.feature
Reverts thebiggive/regression-tests#117
Think I was a bit too hasty merging that - will test manually on staging and run tests in PR branch before merging again next time. Not sure why it's still not working yet.
=> Revert "Revert "Skip test for feature known to be broken - see ticket DON-883""

.circleci/config.yml, features/donation-with-credits.feature, pages/DonateStartPage.js, pages/PledgeFormPage.js, steps/donation.js, steps/hooks.js, support/action.js, support/check.js, support/constants.js, support/mailtrap.js, support/util.js
I expect this will fail, but pushing to Circle CI to see how it fails initially.
=> REG-34: Stop skipping credit donation test

features/donation-as-new-donor-restart-donation.feature, features/donation-as-new-donor-then-register.feature, features/donation-with-credits.feature, features/donation-with-saved-info.feature, features/submit-pledge.feature
=> Temporarily stop checking emails because we have hit Mailtrap limits

features/donation-as-new-donor-restart-donation.feature, features/donation-as-new-donor-then-register.feature, features/donation-with-credits.feature, features/donation-with-saved-info.feature, features/submit-pledge.feature
Reverts thebiggive/regression-tests#132
On Monday our allowance should reset and we can start checking email sending again. Not for merging before that.
=> Revert "Temporarily stop checking emails because we have hit Mailtrap limits"

README.md
Hi,
It would be great if you could perhaps add a link or image to the TestingBot website in the README file.
Many thanks!
=> Add TestingBot Logo to README.md

wdio.testingbot-all.conf.js
Platform combo based on https://testingbot.com/support/getting-started/browsers.html
=> REG-37 – use older Safari 16

pages/DonateStartPage.js, support/action.js, support/check.js
And a few other small improvements
=> DON-1088 – safer input selector checks

.eslintrc.yaml, pages/DonateStartPage.js, steps/donation.js
I'm slightly in two minds having done it, but I was thinking that these function implementations are self-explanatory enough that they may was well be inlined into their callers
=> DON-1088: Refactor, inline simple functions

features/donation-as-new-donor-restart-donation.feature, package.json, steps/donation.js, support/stripe.js, yarn.lock
To make sure we're charging charities the fee we think we're charging them, this adds a check into the "New donor: restarting donation completes successfully" feature that connects to stripe and checks how much we're telling stripe to hold back from their donation.
=> MAt-384: Start checking donations with stripe

features/donation-as-new-donor-restart-donation.feature, steps/donation.js, support/stripe.js
Not very happy with how this looks ad code, especially with the long line in the feature file - feels like that's getting overly detailed if its supposed to be a BDD style test. But not sure what else to do right now.
=> MAT-384: Check additional properties of stripe payment intent

.circleci/config.yml
Was 18 times in daytime schedule plus 5 times in nighttime, now reduced latter to 3 times.
=> REG-39: Reduce scheduled test runs from 23 per day to 21 per day

package.json, steps/donation.js, support/action.js, yarn.lock
(in envs where it isn't yet set to require email verification)
=> Support Register form with submit button having a dynamic label

features/donation-as-new-donor-then-register.feature, features/register-then-create-regular-mandate.feature, features/submit-pledge.feature
Reverts thebiggive/regression-tests#201
=> Revert "REG-41: Temporarily skip tests that rely on email deliverability"

features/donation-as-new-donor-restart-donation.feature
8% of £24,999 is £1,999.92, which is added to gross fee of £450.23 for total £2,450.15
=> BG2-2972 – update expected application fee to account for new tip default
